#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
# 在非 macOS 主机上跳过 Apple 等不可用目标，避免 :libs:* 构建失败
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.stability.nowarn=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true