#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
# Skip Apple targets on non-macOS hosts to avoid build failures
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.stability.nowarn=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Publish
GROUP_ID=com.github.jikun2008.KmpPinYin
VERSION_NAME=0.1.0
