# -*- coding: utf-8 -*-
"""Bootstrap mirror of PinyinTableGenerator.kt.

The sandbox used to first build this repo has no kotlinc/Gradle available, so this
script reproduces, byte-for-byte, the same encoding + rendering that
:libs:generator (PinyinTableGenerator.kt) performs, from the same pinyin-dict.tsv input.
Keep both implementations in sync if the encoding ever changes.
"""
import os

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
EXT_A_START, EXT_A_END = 0x3400, 0x4DBF
MAIN_START, MAIN_END = 0x4E00, 0x9FFF

HERE = os.path.dirname(os.path.abspath(__file__))
TSV = os.path.join(HERE, "..", "src", "main", "resources", "pinyin-dict.tsv")
OUT = os.path.abspath(
    os.path.join(HERE, "..", "..", "tinypinyin-kt", "src", "commonMain", "kotlin")
)


def load_dict():
    d = {}
    with open(TSV, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 3:
                continue
            cp = int(parts[0].strip())
            base = parts[1].strip()
            tone = int(parts[2].strip())
            if base:
                d[cp] = (base, tone)
    return d


def encode(values):
    sb = []
    for v in values:
        sb.append(ALPHABET[(v >> 6) & 0x3F])
        sb.append(ALPHABET[v & 0x3F])
    return "".join(sb)


def wrapped(value):
    lines = [value[i:i + 100] for i in range(0, len(value), 100)]
    out = []
    for i, part in enumerate(lines):
        # Kotlin 只接受“运算符在行尾”的续行写法，所以 + 必须放在上一行末尾。
        suffix = "" if i == len(lines) - 1 else " +"
        out.append('        "%s"%s' % (part, suffix))
    return "\n".join(out)


def main():
    d = load_dict()
    syllables = []
    index = {}
    codes = {}
    for cp in list(range(EXT_A_START, EXT_A_END + 1)) + list(range(MAIN_START, MAIN_END + 1)):
        e = d.get(cp)
        if not e:
            continue
        base, tone = e
        if base not in index:
            index[base] = len(syllables)
            syllables.append(base)
        code = ((index[base] + 1) << 3) | tone
        assert 1 <= code <= 4095, (cp, code)
        codes[cp] = code

    def build(start, end):
        return [codes.get(cp, 0) for cp in range(start, end + 1)]

    extA = build(EXT_A_START, EXT_A_END)
    main_arr = build(MAIN_START, MAIN_END)

    # self verify roundtrip
    for arr in (extA, main_arr):
        s = encode(arr)
        for i in range(len(arr)):
            hi = ALPHABET.index(s[i * 2])
            lo = ALPHABET.index(s[i * 2 + 1])
            assert ((hi << 6) | lo) == arr[i]

    o = []
    a = o.append
    a("package com.github.kmppy.internal")
    a("")
    a("// ============================================================")
    a("// GENERATED by :libs:generator - DO NOT EDIT BY HAND.")
    a("// Source of truth: libs/generator/src/main/resources/pinyin-dict.tsv")
    a("// Regenerate: ./gradlew :libs:generator:run")
    a("// ============================================================")
    a("")
    a("internal object PinyinTable {")
    a("")
    a('    private const val ALPHABET = "%s"' % ALPHABET)
    a("")
    a("    internal const val EXT_A_START = %d" % EXT_A_START)
    a("    internal const val EXT_A_END = %d" % EXT_A_END)
    a("    internal const val MAIN_START = %d" % MAIN_START)
    a("    internal const val MAIN_END = %d" % MAIN_END)
    a("")
    a("    /** Tone-less ASCII syllables; 'v' represents u-umlaut (u after n/l). */")
    a('    private const val SYLLABLES_STRING = "%s"' % " ".join(syllables))
    a("")
    a("    private const val EXT_A_TABLE_STRING =")
    a(wrapped(encode(extA)))
    a("")
    a("    private const val MAIN_TABLE_STRING =")
    a(wrapped(encode(main_arr)))
    a("")
    a('    internal val syllables: Array<String> by lazy { SYLLABLES_STRING.split(" ").toTypedArray() }')
    a("")
    a("    private val extATable: ShortArray by lazy { decode(EXT_A_TABLE_STRING) }")
    a("    private val mainTable: ShortArray by lazy { decode(MAIN_TABLE_STRING) }")
    a("")
    a("    private fun decode(s: String): ShortArray {")
    a("        val out = ShortArray(s.length / 2)")
    a("        for (i in out.indices) {")
    a("            val hi = ALPHABET.indexOf(s[i * 2])")
    a("            val lo = ALPHABET.indexOf(s[i * 2 + 1])")
    a("            out[i] = ((hi shl 6) or lo).toShort()")
    a("        }")
    a("        return out")
    a("    }")
    a("")
    a('    /** 12-bit packed code for [c]; 0 means "not covered by the table". */')
    a("    internal fun codeOf(c: Char): Int {")
    a("        val cp = c.code")
    a("        return when (cp) {")
    a("            in MAIN_START..MAIN_END -> mainTable[cp - MAIN_START].toInt() and 0xFFFF")
    a("            in EXT_A_START..EXT_A_END -> extATable[cp - EXT_A_START].toInt() and 0xFFFF")
    a("            else -> 0")
    a("        }")
    a("    }")
    a("}")

    target_dir = os.path.join(OUT, "com", "github", "kmppy", "internal")
    os.makedirs(target_dir, exist_ok=True)
    path = os.path.join(target_dir, "PinyinTable.kt")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(o) + "\n")

    print("Wrote %s" % path)
    print("syllables=%d extA=%d main=%d mapped=%d" % (
        len(syllables), len(extA), len(main_arr), len(codes)))


if __name__ == "__main__":
    main()
